kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag12-sep16-2-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag12-sep16-2-dsp-job
    namespace: rag12-sep16-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag12-sep16-2-dsp-job-role